name: tta

services:
  tta-web:
    image: ghcr.io/litt1estar/tta-landingpage:latest
    restart: unless-stopped
    expose:
      - "80"

networks:
  default:
    name: cmm_default
    external: true
